<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find boat_description)/urdf/common_inertia.xacro"/>
    <xacro:macro name="base_xacro" params="length radius">
        <!-- ground -->
        <link name="ground_link"/> 

        <!-- robot body -->
        <link name="base_link">
            <!-- visual of parts -->
            <visual>
                <!-- offset and rotation relative to self center -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- geometry description -->
                <geometry>
                    <!-- box/cylinder/... -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- Material description -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <collision>
                <!-- offset and rotation relative to self center -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- geometry description -->
                <geometry>
                    <!-- box/cylinder/... -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- Material description -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>

            
        </link>

        <joint name="joint_name" type="fixed">
            <origin xyz="0.0 0.0 ${length/2+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="ground_link"/>
            <child link="base_link"/>
        </joint>
    </xacro:macro>
</robot>
